// <auto-generated />
namespace SCCBakery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class connectToDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(connectToDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201809030049133_connectToDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
